; Auto-generated. Do not edit!


(cl:in-package moveit_tutorials-msg)


;//! \htmlinclude ValidJointsFeedback.msg.html

(cl:defclass <ValidJointsFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ValidJointsFeedback (<ValidJointsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ValidJointsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ValidJointsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name moveit_tutorials-msg:<ValidJointsFeedback> is deprecated: use moveit_tutorials-msg:ValidJointsFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ValidJointsFeedback>) ostream)
  "Serializes a message object of type '<ValidJointsFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ValidJointsFeedback>) istream)
  "Deserializes a message object of type '<ValidJointsFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ValidJointsFeedback>)))
  "Returns string type for a message object of type '<ValidJointsFeedback>"
  "moveit_tutorials/ValidJointsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ValidJointsFeedback)))
  "Returns string type for a message object of type 'ValidJointsFeedback"
  "moveit_tutorials/ValidJointsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ValidJointsFeedback>)))
  "Returns md5sum for a message object of type '<ValidJointsFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ValidJointsFeedback)))
  "Returns md5sum for a message object of type 'ValidJointsFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ValidJointsFeedback>)))
  "Returns full string definition for message of type '<ValidJointsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ValidJointsFeedback)))
  "Returns full string definition for message of type 'ValidJointsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ValidJointsFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ValidJointsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ValidJointsFeedback
))
