; Auto-generated. Do not edit!


(cl:in-package moveit_tutorials-msg)


;//! \htmlinclude ValidJointsResult.msg.html

(cl:defclass <ValidJointsResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ValidJointsResult (<ValidJointsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ValidJointsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ValidJointsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name moveit_tutorials-msg:<ValidJointsResult> is deprecated: use moveit_tutorials-msg:ValidJointsResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ValidJointsResult>) ostream)
  "Serializes a message object of type '<ValidJointsResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ValidJointsResult>) istream)
  "Deserializes a message object of type '<ValidJointsResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ValidJointsResult>)))
  "Returns string type for a message object of type '<ValidJointsResult>"
  "moveit_tutorials/ValidJointsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ValidJointsResult)))
  "Returns string type for a message object of type 'ValidJointsResult"
  "moveit_tutorials/ValidJointsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ValidJointsResult>)))
  "Returns md5sum for a message object of type '<ValidJointsResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ValidJointsResult)))
  "Returns md5sum for a message object of type 'ValidJointsResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ValidJointsResult>)))
  "Returns full string definition for message of type '<ValidJointsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ValidJointsResult)))
  "Returns full string definition for message of type 'ValidJointsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ValidJointsResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ValidJointsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ValidJointsResult
))
