; Auto-generated. Do not edit!


(cl:in-package moveit_tutorials-msg)


;//! \htmlinclude ValidJointsGoal.msg.html

(cl:defclass <ValidJointsGoal> (roslisp-msg-protocol:ros-message)
  ((valid_joint_values
    :reader valid_joint_values
    :initarg :valid_joint_values
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ValidJointsGoal (<ValidJointsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ValidJointsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ValidJointsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name moveit_tutorials-msg:<ValidJointsGoal> is deprecated: use moveit_tutorials-msg:ValidJointsGoal instead.")))

(cl:ensure-generic-function 'valid_joint_values-val :lambda-list '(m))
(cl:defmethod valid_joint_values-val ((m <ValidJointsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader moveit_tutorials-msg:valid_joint_values-val is deprecated.  Use moveit_tutorials-msg:valid_joint_values instead.")
  (valid_joint_values m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ValidJointsGoal>) ostream)
  "Serializes a message object of type '<ValidJointsGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'valid_joint_values))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'valid_joint_values))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ValidJointsGoal>) istream)
  "Deserializes a message object of type '<ValidJointsGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'valid_joint_values) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'valid_joint_values)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ValidJointsGoal>)))
  "Returns string type for a message object of type '<ValidJointsGoal>"
  "moveit_tutorials/ValidJointsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ValidJointsGoal)))
  "Returns string type for a message object of type 'ValidJointsGoal"
  "moveit_tutorials/ValidJointsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ValidJointsGoal>)))
  "Returns md5sum for a message object of type '<ValidJointsGoal>"
  "726551018de18a5486e36fb7fd3f6c81")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ValidJointsGoal)))
  "Returns md5sum for a message object of type 'ValidJointsGoal"
  "726551018de18a5486e36fb7fd3f6c81")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ValidJointsGoal>)))
  "Returns full string definition for message of type '<ValidJointsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] valid_joint_values~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ValidJointsGoal)))
  "Returns full string definition for message of type 'ValidJointsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] valid_joint_values~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ValidJointsGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'valid_joint_values) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ValidJointsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ValidJointsGoal
    (cl:cons ':valid_joint_values (valid_joint_values msg))
))
