// Generated by gencpp from file moveit_tutorials/GetCurrentJointVelResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETCURRENTJOINTVELRESPONSE_H
#define MOVEIT_TUTORIALS_MESSAGE_GETCURRENTJOINTVELRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_tutorials
{
template <class ContainerAllocator>
struct GetCurrentJointVelResponse_
{
  typedef GetCurrentJointVelResponse_<ContainerAllocator> Type;

  GetCurrentJointVelResponse_()
    : current_joint_vel()  {
    }
  GetCurrentJointVelResponse_(const ContainerAllocator& _alloc)
    : current_joint_vel(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _current_joint_vel_type;
  _current_joint_vel_type current_joint_vel;





  typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentJointVelResponse_

typedef ::moveit_tutorials::GetCurrentJointVelResponse_<std::allocator<void> > GetCurrentJointVelResponse;

typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentJointVelResponse > GetCurrentJointVelResponsePtr;
typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentJointVelResponse const> GetCurrentJointVelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.current_joint_vel == rhs.current_joint_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d32d78f4d7ef4d386bfa163951babe5";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d32d78f4d7ef4d3ULL;
  static const uint64_t static_value2 = 0x86bfa163951babe5ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_tutorials/GetCurrentJointVelResponse";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] current_joint_vel\n"
;
  }

  static const char* value(const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_joint_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentJointVelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_tutorials::GetCurrentJointVelResponse_<ContainerAllocator>& v)
  {
    s << indent << "current_joint_vel[]" << std::endl;
    for (size_t i = 0; i < v.current_joint_vel.size(); ++i)
    {
      s << indent << "  current_joint_vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.current_joint_vel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETCURRENTJOINTVELRESPONSE_H
