// Generated by gencpp from file moveit_tutorials/GetCurrentImage.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGE_H
#define MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGE_H

#include <ros/service_traits.h>


#include <moveit_tutorials/GetCurrentImageRequest.h>
#include <moveit_tutorials/GetCurrentImageResponse.h>


namespace moveit_tutorials
{

struct GetCurrentImage
{

typedef GetCurrentImageRequest Request;
typedef GetCurrentImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentImage
} // namespace moveit_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentImage > {
  static const char* value()
  {
    return "cb21fca2e1d6a2c2ac7fcf25b60e6837";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImage&) { return value(); }
};

template<>
struct DataType< ::moveit_tutorials::GetCurrentImage > {
  static const char* value()
  {
    return "moveit_tutorials/GetCurrentImage";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImage&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImageRequest> should match
// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImage >
template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GetCurrentImage >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GetCurrentImageRequest> should match
// service_traits::DataType< ::moveit_tutorials::GetCurrentImage >
template<>
struct DataType< ::moveit_tutorials::GetCurrentImageRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GetCurrentImage >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImageResponse> should match
// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImage >
template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GetCurrentImage >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GetCurrentImageResponse> should match
// service_traits::DataType< ::moveit_tutorials::GetCurrentImage >
template<>
struct DataType< ::moveit_tutorials::GetCurrentImageResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GetCurrentImage >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGE_H
