// Generated by gencpp from file moveit_tutorials/GetCurrentImageData.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGEDATA_H
#define MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGEDATA_H

#include <ros/service_traits.h>


#include <moveit_tutorials/GetCurrentImageDataRequest.h>
#include <moveit_tutorials/GetCurrentImageDataResponse.h>


namespace moveit_tutorials
{

struct GetCurrentImageData
{

typedef GetCurrentImageDataRequest Request;
typedef GetCurrentImageDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentImageData
} // namespace moveit_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentImageData > {
  static const char* value()
  {
    return "06552b34b97c1365790de0d089ef0bec";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImageData&) { return value(); }
};

template<>
struct DataType< ::moveit_tutorials::GetCurrentImageData > {
  static const char* value()
  {
    return "moveit_tutorials/GetCurrentImageData";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImageData&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImageDataRequest> should match
// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImageData >
template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentImageDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GetCurrentImageData >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GetCurrentImageDataRequest> should match
// service_traits::DataType< ::moveit_tutorials::GetCurrentImageData >
template<>
struct DataType< ::moveit_tutorials::GetCurrentImageDataRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GetCurrentImageData >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImageDataResponse> should match
// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentImageData >
template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentImageDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GetCurrentImageData >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GetCurrentImageDataResponse> should match
// service_traits::DataType< ::moveit_tutorials::GetCurrentImageData >
template<>
struct DataType< ::moveit_tutorials::GetCurrentImageDataResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GetCurrentImageData >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentImageDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGEDATA_H
