// Generated by gencpp from file moveit_tutorials/GetCurrentImageDataResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGEDATARESPONSE_H
#define MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGEDATARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_tutorials
{
template <class ContainerAllocator>
struct GetCurrentImageDataResponse_
{
  typedef GetCurrentImageDataResponse_<ContainerAllocator> Type;

  GetCurrentImageDataResponse_()
    : current_image()  {
    }
  GetCurrentImageDataResponse_(const ContainerAllocator& _alloc)
    : current_image(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _current_image_type;
  _current_image_type current_image;





  typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentImageDataResponse_

typedef ::moveit_tutorials::GetCurrentImageDataResponse_<std::allocator<void> > GetCurrentImageDataResponse;

typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentImageDataResponse > GetCurrentImageDataResponsePtr;
typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentImageDataResponse const> GetCurrentImageDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.current_image == rhs.current_image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06552b34b97c1365790de0d089ef0bec";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06552b34b97c1365ULL;
  static const uint64_t static_value2 = 0x790de0d089ef0becULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_tutorials/GetCurrentImageDataResponse";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] current_image\n"
"\n"
;
  }

  static const char* value(const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentImageDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_tutorials::GetCurrentImageDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "current_image[]" << std::endl;
    for (size_t i = 0; i < v.current_image.size(); ++i)
    {
      s << indent << "  current_image[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current_image[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETCURRENTIMAGEDATARESPONSE_H
