// Generated by gencpp from file moveit_tutorials/GetCurrentCountResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETCURRENTCOUNTRESPONSE_H
#define MOVEIT_TUTORIALS_MESSAGE_GETCURRENTCOUNTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_tutorials
{
template <class ContainerAllocator>
struct GetCurrentCountResponse_
{
  typedef GetCurrentCountResponse_<ContainerAllocator> Type;

  GetCurrentCountResponse_()
    : count(0)  {
    }
  GetCurrentCountResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentCountResponse_

typedef ::moveit_tutorials::GetCurrentCountResponse_<std::allocator<void> > GetCurrentCountResponse;

typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentCountResponse > GetCurrentCountResponsePtr;
typedef boost::shared_ptr< ::moveit_tutorials::GetCurrentCountResponse const> GetCurrentCountResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_tutorials/GetCurrentCountResponse";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 count\n"
;
  }

  static const char* value(const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentCountResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_tutorials::GetCurrentCountResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETCURRENTCOUNTRESPONSE_H
