// Generated by gencpp from file moveit_tutorials/GetCurrentJointVel.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETCURRENTJOINTVEL_H
#define MOVEIT_TUTORIALS_MESSAGE_GETCURRENTJOINTVEL_H

#include <ros/service_traits.h>


#include <moveit_tutorials/GetCurrentJointVelRequest.h>
#include <moveit_tutorials/GetCurrentJointVelResponse.h>


namespace moveit_tutorials
{

struct GetCurrentJointVel
{

typedef GetCurrentJointVelRequest Request;
typedef GetCurrentJointVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentJointVel
} // namespace moveit_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentJointVel > {
  static const char* value()
  {
    return "1d32d78f4d7ef4d386bfa163951babe5";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentJointVel&) { return value(); }
};

template<>
struct DataType< ::moveit_tutorials::GetCurrentJointVel > {
  static const char* value()
  {
    return "moveit_tutorials/GetCurrentJointVel";
  }

  static const char* value(const ::moveit_tutorials::GetCurrentJointVel&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentJointVelRequest> should match
// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentJointVel >
template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentJointVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GetCurrentJointVel >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentJointVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GetCurrentJointVelRequest> should match
// service_traits::DataType< ::moveit_tutorials::GetCurrentJointVel >
template<>
struct DataType< ::moveit_tutorials::GetCurrentJointVelRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GetCurrentJointVel >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentJointVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentJointVelResponse> should match
// service_traits::MD5Sum< ::moveit_tutorials::GetCurrentJointVel >
template<>
struct MD5Sum< ::moveit_tutorials::GetCurrentJointVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GetCurrentJointVel >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentJointVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GetCurrentJointVelResponse> should match
// service_traits::DataType< ::moveit_tutorials::GetCurrentJointVel >
template<>
struct DataType< ::moveit_tutorials::GetCurrentJointVelResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GetCurrentJointVel >::value();
  }
  static const char* value(const ::moveit_tutorials::GetCurrentJointVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETCURRENTJOINTVEL_H
