// Generated by gencpp from file moveit_tutorials/GettfPose.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETTFPOSE_H
#define MOVEIT_TUTORIALS_MESSAGE_GETTFPOSE_H

#include <ros/service_traits.h>


#include <moveit_tutorials/GettfPoseRequest.h>
#include <moveit_tutorials/GettfPoseResponse.h>


namespace moveit_tutorials
{

struct GettfPose
{

typedef GettfPoseRequest Request;
typedef GettfPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GettfPose
} // namespace moveit_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_tutorials::GettfPose > {
  static const char* value()
  {
    return "a4fcab672ea64ead4d870b0730e4c129";
  }

  static const char* value(const ::moveit_tutorials::GettfPose&) { return value(); }
};

template<>
struct DataType< ::moveit_tutorials::GettfPose > {
  static const char* value()
  {
    return "moveit_tutorials/GettfPose";
  }

  static const char* value(const ::moveit_tutorials::GettfPose&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_tutorials::GettfPoseRequest> should match
// service_traits::MD5Sum< ::moveit_tutorials::GettfPose >
template<>
struct MD5Sum< ::moveit_tutorials::GettfPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GettfPose >::value();
  }
  static const char* value(const ::moveit_tutorials::GettfPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GettfPoseRequest> should match
// service_traits::DataType< ::moveit_tutorials::GettfPose >
template<>
struct DataType< ::moveit_tutorials::GettfPoseRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GettfPose >::value();
  }
  static const char* value(const ::moveit_tutorials::GettfPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_tutorials::GettfPoseResponse> should match
// service_traits::MD5Sum< ::moveit_tutorials::GettfPose >
template<>
struct MD5Sum< ::moveit_tutorials::GettfPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorials::GettfPose >::value();
  }
  static const char* value(const ::moveit_tutorials::GettfPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorials::GettfPoseResponse> should match
// service_traits::DataType< ::moveit_tutorials::GettfPose >
template<>
struct DataType< ::moveit_tutorials::GettfPoseResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorials::GettfPose >::value();
  }
  static const char* value(const ::moveit_tutorials::GettfPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETTFPOSE_H
