// Generated by gencpp from file moveit_tutorials/GettfPoseResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_GETTFPOSERESPONSE_H
#define MOVEIT_TUTORIALS_MESSAGE_GETTFPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_tutorials
{
template <class ContainerAllocator>
struct GettfPoseResponse_
{
  typedef GettfPoseResponse_<ContainerAllocator> Type;

  GettfPoseResponse_()
    : trans()
    , rot()  {
    }
  GettfPoseResponse_(const ContainerAllocator& _alloc)
    : trans(_alloc)
    , rot(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _trans_type;
  _trans_type trans;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _rot_type;
  _rot_type rot;





  typedef boost::shared_ptr< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GettfPoseResponse_

typedef ::moveit_tutorials::GettfPoseResponse_<std::allocator<void> > GettfPoseResponse;

typedef boost::shared_ptr< ::moveit_tutorials::GettfPoseResponse > GettfPoseResponsePtr;
typedef boost::shared_ptr< ::moveit_tutorials::GettfPoseResponse const> GettfPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.trans == rhs.trans &&
    lhs.rot == rhs.rot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator1> & lhs, const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4fcab672ea64ead4d870b0730e4c129";
  }

  static const char* value(const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4fcab672ea64eadULL;
  static const uint64_t static_value2 = 0x4d870b0730e4c129ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_tutorials/GettfPoseResponse";
  }

  static const char* value(const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] trans\n"
"float64[] rot\n"
"\n"
;
  }

  static const char* value(const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trans);
      stream.next(m.rot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GettfPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_tutorials::GettfPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "trans[]" << std::endl;
    for (size_t i = 0; i < v.trans.size(); ++i)
    {
      s << indent << "  trans[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.trans[i]);
    }
    s << indent << "rot[]" << std::endl;
    for (size_t i = 0; i < v.rot.size(); ++i)
    {
      s << indent << "  rot[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rot[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_GETTFPOSERESPONSE_H
