// Generated by gencpp from file moveit_tutorials/ValidJointsActionGoal.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIALS_MESSAGE_VALIDJOINTSACTIONGOAL_H
#define MOVEIT_TUTORIALS_MESSAGE_VALIDJOINTSACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <moveit_tutorials/ValidJointsGoal.h>

namespace moveit_tutorials
{
template <class ContainerAllocator>
struct ValidJointsActionGoal_
{
  typedef ValidJointsActionGoal_<ContainerAllocator> Type;

  ValidJointsActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ValidJointsActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::moveit_tutorials::ValidJointsGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ValidJointsActionGoal_

typedef ::moveit_tutorials::ValidJointsActionGoal_<std::allocator<void> > ValidJointsActionGoal;

typedef boost::shared_ptr< ::moveit_tutorials::ValidJointsActionGoal > ValidJointsActionGoalPtr;
typedef boost::shared_ptr< ::moveit_tutorials::ValidJointsActionGoal const> ValidJointsActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator1> & lhs, const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator1> & lhs, const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18a164c3ce824b1f565a5fa001de5916";
  }

  static const char* value(const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18a164c3ce824b1fULL;
  static const uint64_t static_value2 = 0x565a5fa001de5916ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_tutorials/ValidJointsActionGoal";
  }

  static const char* value(const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ValidJointsGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: moveit_tutorials/ValidJointsGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64[] valid_joint_values\n"
;
  }

  static const char* value(const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValidJointsActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_tutorials::ValidJointsActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::moveit_tutorials::ValidJointsGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TUTORIALS_MESSAGE_VALIDJOINTSACTIONGOAL_H
